### ISSUE TITLE
Depracation warning for filesystem cookbook

### ISSUE THREAD

**Issue by glajchs** [sous-chefs/filesystem#22]
You get the following warning now in chef:
  Cannot specify both default and name_property together on property name of resource filesystem_create_all_from_key. Only one (name_property) will be obeyed. In Chef 13, this will become an error. Please remove one or the other from the property. at 1 location:
    - /var/chef/cache/cookbooks/filesystem/resources/create_all_from_key.rb:25:in `class_from_file'

I think you just need to rework how that line is done to be compatible with current/future chef versions.

**Comment by rshade** [comment]
This should no longer be an issue, can you verify?
