### ISSUE TITLE
format and mount device

### ISSUE THREAD

**Issue by jeusdi** [sous-chefs/filesystem#33]
I need to perform these instructions in order to mount a device:

    mkfs.ext4 -F /dev/disk/by-id/scsi-0DO_Volume_baz

    mkdir -p /mnt/baz;
    mount -o discard,defaults /dev/disk/by-id/scsi-0DO_Volume_baz /mnt/baz
    echo /dev/disk/by-id/scsi-0DO_Volume_baz /mnt/baz ext4 defaults,nofail,discard 0 0 | sudo tee -a /etc/fstab

Shortly, I need to format the device and then mount it.

Is it possible to do that using this cookbook?

**Comment by donwlewis** [comment]
Yes.  This can be done with this cookbook.

**Comment by jeusdi** [comment]
Could you provide me any helping stuff code?

**Comment by donwlewis** [comment]
The document is pretty clear, but it would look something like this for you:

```ruby
filesystem 'baz' do
  fstype 'ext4'
  device '/dev/disk/by-id/scsi-0DO_Volume_baz'
  mount '/mnt/baz'
  options 'defaults,nofail,discard'
  action [:create, :enable, :mount]
end
```

That would be leveraging this cookbook to accomplish this, so you would have to make it dependent in your wrapper cookbook.

**Comment by MarkGibbons** [comment]
Question answered. Closing the issue.
