### ISSUE TITLE
Request: tag/release 0.12.1

### ISSUE THREAD

**Issue by jeffb-stell** [sous-chefs/filesystem#39]
### Cookbook version
0.12.1

### Chef-client version
any

### Platform Details
any

### Scenario:
install filesystem v0.12.1 cookbook from supermarket

### Steps to Reproduce:
attempt to install latest filesystem cookbook from supermarket

### Expected Result:
installs 0.12.1

### Actual Result:
installs 0.12.0

**Comment by damacus** [comment]
Released under [v1.0.0](https://supermarket.chef.io/cookbooks/filesystem/versions/1.0.0)

Thanks for the push.
