### ISSUE TITLE
Default recipe broken on RedHat 7

### ISSUE THREAD

**Issue by neufeldtech** [sous-chefs/filesystem#40]
### Cookbook version
0.12.1

### Chef-client version
12.21.14

### Platform Details
Amazon AWS
Red Hat Enterprise Linux Server 7.4 (Maipo)
RHEL-7.4_HVM_GA-20170808-x86_64-2-Hourly2-GP2 (ami-9fa343e7)

### Scenario:
The default recipe is broken on RHEL 7.4 because the xfsprogs-devel package is no longer supported.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/migration_planning_guide/sect-red_hat_enterprise_linux-migration_planning_guide-removed_packages

### Steps to Reproduce:
Launch Amazon EC2 instance with AMI ami-9fa343e7 (Rhel 7.4)
Include `filesystem::default` in the run list
Run `chef-client`
Node will not converge because xfsprogs-devel cannot be installed

### Expected Result:
Expect chef to converge cleanly.

### Actual Result:
`chef-client` does not complete and node fails converging because xfsprogs-devel cannot be installed.

```
Converging 24 resources
Recipe: filesystem::default
  * yum_package[xfsprogs, xfsprogs-devel] action install[2017-11-06T21:36:35+00:00] INFO: Processing yum_package[xfsprogs, xfsprogs-devel] action install (filesystem::default line 23)

    * No candidate version available for xfsprogs-devel
    ================================================================================
    Error executing action `install` on resource 'yum_package[xfsprogs, xfsprogs-devel]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    No candidate version available for xfsprogs-devel

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/filesystem/recipes/default.rb

     23:   package %w(xfsprogs xfsprogs-devel)
     24: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/filesystem/recipes/default.rb:23:in `from_file'

    yum_package("xfsprogs, xfsprogs-devel") do
      package_name ["xfsprogs", "xfsprogs-devel"]
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "filesystem"
      recipe_name "default"
      flush_cache {:before=>false, :after=>false}
      arch [nil, nil]
    end

    System Info:
    ------------
    chef_version=12.21.14
    platform=redhat
    platform_version=7.4
    ruby=ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-linux]
    program_name=chef-client worker: ppid=84403;start=21:36:27;
    executable=/opt/chef/bin/chef-client
```

**Comment by josephholsten** [comment]
@neufeldtech is it sufficient to just remove that package from the list?

Also, it looks like we’re testing centos 7, are we failing to catch this error in the tests? Any chance you can update the tests to fail the way you’re seeing? Please let me know if you need a helping hand.

**Comment by neufeldtech** [comment]
@josephholsten ,
I did a bit of testing and it should be sufficient to remove the package from the list. I added a RHEL 7 box to the vagrant boxes in #41 that can reproduce the failure, if the xfsprogs-devel package is included.
