### ISSUE TITLE
Request: please tag and release 0.13.0

### ISSUE THREAD

**Issue by stuart12** [sous-chefs/filesystem#45]
### Cookbook version
0.12.0

### Scenario:
I want to install an up to date version of filesystem with recent commits including 5d37a603c3.

### Steps to Reproduce:
Install filesystem

### Expected Result:
Install filesystem 0.13.0 with commit 5d37a603c3

### Actual Result:
Installs filesystem 0.12.0 without commit 5d37a603c3

**Comment by gordonbondon** [comment]
Can we get a release with latest changes?

**Comment by damacus** [comment]
Released under [v1.0.0](https://supermarket.chef.io/cookbooks/filesystem/versions/1.0.0)

**Comment by damacus** [comment]
Thanks for the push here!
