### ISSUE TITLE
Improve handling of nonexistent devices

### ISSUE THREAD

**Issue by rbcrwd** [sous-chefs/filesystem#47]
### Cookbook version
0.12.0

### Chef-client version
13.7.16

### Platform Details
Ubunutu/16 LTS
AWS EC2

### Scenario:
I'm building some systems where backing block devices for certain filesystems may not exist. Regardless of how good an idea that is, I found use for writing a wrapper around recipe[filesystem] that didn't attempt to handle a filesystem where the backing device didn't exist.  This would probably be better handled as a per-label attribute (e.g. a "wait" attribute on a label).

I'm prepared to write a PR for the above behavior (adding a 'wait' feature), but would you consider this even useful?

**Comment by MarkGibbons** [comment]
If I understand the request the processing requested is:
   Block device to be used by the specified by name or label property doesn't exist
   If ignore flag set, wait property suggested, exit without processing

The device to use can be specified a couple of different ways, these actions may make sense to fulfill the request.
    a file => fail 
    LVM volume group => fail if the volume group doesn't exist
    uuid - "/dev/disk/by-uuid" => do nothing if flag set && does not exist
    a device - "/dev/*" => do nothing if flag set && does not exist
    a label mapping - "/dev/mapper/". => do nothing if flag set && does not exist

**Comment by MarkGibbons** [comment]
fixed by #89.  Added a device_defer attribute

**Comment by rbcrwd** [comment]
Thanks, yes - that will satisfy my intent

**Comment by MarkGibbons** [comment]
Cool, implemented as the device_defer attribute.  Thanks for responding.
