### ISSUE TITLE
Mounting nfs filesystem not working

### ISSUE THREAD

**Issue by bilby91** [sous-chefs/filesystem#54]
### Cookbook version
1.0.0

### Chef-client version
14.12.9

### Platform Details
Ubuntu 18

### Scenario:
Mount a nfs filesystem, specially AWS efs filesystem.

### Steps to Reproduce:
Use the following attributes:
```
    "filesystems": {
      "postgres_archive": {
        "device": "XXXXX.efs.us-east-1.amazonaws.com:/",
        "mount": "/mnt/mount_point",
        "package": "nfs-common",
        "fstype": "nfs",
        "options": "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      }
```
### Expected Result:
The `mount` action is not ignored and the filesystem is mounted.

### Actual Result:
The `mount` action is ignored because of the `only_if` https://github.com/sous-chefs/filesystem/blob/master/providers/default.rb#L210

I'm not sure if this is expected behaviour but `test -b fs-dns` always returns status code 1 when the fs is actually available.

**Comment by MarkGibbons** [comment]
Nice diagnosis of the problem.  test -b looks for a block device.  The embedded mount command would need work to mount NFS file systems.  This cookbook is really designed to manage block devices, not NFS.  There is an embedded mount resource, but the mount resource can be called by itself without using filesystem.

**Comment by MarkGibbons** [comment]
#90 should resolve mounting an NFS filesystem.  Support for NFS is going to be limited though.
