### ISSUE TITLE
 No candidate version available for xfsprogs

### ISSUE THREAD

**Issue by venkatakrishnachaparala** [sous-chefs/filesystem#73]
yum_package[xfsprogs] action install[2020-03-19T09:54:31+00:00] INFO: Processing yum_package[xfsprogs] action install (filesystem::default line 23)

           * No candidate version available for xfsprogs
           ================================================================================
           Error executing action `install` on resource 'yum_package[xfsprogs]'
           ================================================================================

           Chef::Exceptions::Package
           -------------------------
           No candidate version available for xfsprogs

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/filesystem/recipes/default.rb

            23:   package %w(xfsprogs)
            24: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/filesystem/recipes/default.rb:23:in `from_file'

           yum_package("xfsprogs") do
             package_name ["xfsprogs"]
             action [:install]
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "filesystem"
             recipe_name "default"
           end

           System Info:
           ------------
           chef_version=14.12.9
           platform=redhat
           platform_version=6.9
           ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client

**Comment by damacus** [comment]
Are you using anything similar to satellite? Your yum repo might be out of date.

**Comment by venkatakrishnachaparala** [comment]
not a satellite server  and yum repo is up to date

[root@ip-10-61-11-23 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.10 (Santiago)
[root@ip-10-61-11-23 ~]#

[root@ip-10-61-11-23 ~]# yum search xfsprogs
Loaded plugins: amazon-id, search-disabled-repos, security
rhui-REGION-rhel-server-releases                                                                                                                 | 2.0 kB     00:00

rhui-REGION-rhel-server-releases/primary                              80% [===============================================-           ]  0.0 B/s |  34 MB     --:-- ETA rhui-REGION-rhel-server-releases/primary                                                                                                         |  41 MB     00:00

rhui-REGION-rhel-server-releases                                                                                                                            21031/21031 rhui-REGION-rhel-server-rh-common                                                                                                                | 2.1 kB     00:00

rhui-REGION-rhel-server-rh-common/primary                                                                                                        |  38 kB     00:00

rhui-REGION-rhel-server-rh-common                                                                                                                               129/129 rhui-client-config-server-6                                                                                                                      | 2.1 kB     00:00

rhui-client-config-server-6/primary                                                                                                              | 1.7 kB     00:00

rhui-client-config-server-6                                                                                                                                         6/6 Warning: No matches found for: xfsprogs
No Matches found
[root@ip-10-61-11-23 ~]#

**Comment by MarkGibbons** [comment]
XFS is part of rhel7 and up.
Red Hat Scalable File System can be used on rhel 5 an rhel 6 servers.

The red-hot site says.

Access

    Red Hat Scalable File System requires a subscription entitlement
   Contact Red Hat Sales for pricing information for the subscriptions
   Red Hat Scalable File System is only delivered online through the Red Hat Network
RHN Satellite customers:
   After purchasing Scalable File System subscriptions, a new satellite certificate will need to be procured and activated
  After that, channel profiles will need to be updated to include the new channel

Getting access to xfsprogs isn't really a filesystem cookbook problem.  XFS support needs to be available.

I'm going to close this request as being out of scope for the cookbook.  

Mark
